CREATE TABLE IF NOT EXISTS app_users (
    email VARCHAR(320) PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS trip_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(320) NOT NULL,
    trip_json CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_trip_user FOREIGN KEY (user_email) REFERENCES app_users(email)
);
CREATE INDEX IF NOT EXISTS idx_trip_history_user ON trip_history(user_email, id);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token VARCHAR(80) PRIMARY KEY,
    user_email VARCHAR(320) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_auth_session_user FOREIGN KEY (user_email) REFERENCES app_users(email) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_email);
